[build]
rustflags = ["-C", "link-arg=-Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/python@3.14/lib"]

[env]
PYO3_PYTHON = "/home/linuxbrew/.linuxbrew/bin/python3"
LD_LIBRARY_PATH = "/home/linuxbrew/.linuxbrew/opt/python@3.14/lib"
